apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  AWS_REGION: "us-east-1"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
